#!/usr/bin/env ruby -w

require 'fileutils'
require_relative 'remote_host'
require 'yaml'

FileUtils.mkdir_p('data')
Dir.chdir('data')
hosts_to_monitor = ['118.178.127.36', '120.26.103.14']
hosts_to_monitor.each do |host|
  logins = RemoteHost.new(host).last_logins
  dump_file = host + Time.now.strftime('.%Y%m%dT%H%M%S.yaml')
  File.open(dump_file, 'w') { |f| YAML.dump(logins, f) }
end
